-- CombatSession :: Commands
--
-- Slash interface over the data API and the recorder.

local ADDON, ns = ...

local function CountKeys(t)
    local n = 0
    for _ in pairs(t or {}) do n = n + 1 end
    return n
end

local function Status()
    local db = ns.db
    if not db then ns:Print("not initialised") return end

    local name, instanceType, instanceID = GetInstanceInfo()
    ns:Print(("|cffffffffv%s|r"):format(ns.VERSION))

    -- Two independent subsystems. Recorder counts cover matches played with this
    -- addon enabled and never change when sessions are processed; session counts
    -- cover data delivered by the application.
    ns:Print(("  |cff99ccffsessions|r  %d viewable, %d queued (cap %d)")
        :format(#ns.API:GetViewable(), #ns.API:GetPending(), ns.API:GetMaxSessions()))
    ns:Print(("             holding %d cached, declining below: %s")
        :format(CountKeys(db.cache),
                db.oldestWanted ~= "" and db.oldestWanted or "|cff888888nothing|r"))
    ns:Print(("  |cff99ccffrecorder|r  %d match(es) recorded live, %d trace entries")
        :format(#db.matches, #db.trace))
    ns:Print(("  |cff99ccffzone|r      %s (%s, id %s), logging %s")
        :format(tostring(name), tostring(instanceType), tostring(instanceID),
                LoggingCombat() and "|cff33ff33ON|r" or "|cffff5555OFF|r"))
    -- Advanced logging is reported next to autoLog because it is the one
    -- setting that can silently make every recorded log useless.
    ns:Print(("  |cff99ccffsettings|r  autoLog %s, advanced %s, debug %s")
        :format(tostring(db.settings.autoLog),
                (GetCVar and GetCVar("advancedCombatLogging") == "1")
                    and "|cff33ff33ON|r" or "|cffff5555OFF|r",
                tostring(db.settings.debug)))

    local last = db.matches[#db.matches]
    if last then
        ns:Print(("last: %s  %s  %s  roster=%d  %s")
            :format(date("%Y-%m-%d %H:%M", last.startedAt),
                    tostring(last.mapName),
                    last.isRated and "|cffffcc00RATED|r" or "unrated",
                    last.roster and #last.roster or 0,
                    last.abandoned and "|cffff5555ABANDONED|r" or "complete"))
    end
end

-- Prints the tail of the instrumentation ring. This is what settles the
-- multi-round event ordering question once a Solo Shuffle has been played.
local function DumpTrace(count)
    local db = ns.db
    if not db or #db.trace == 0 then ns:Print("no trace entries") return end

    count = math.min(tonumber(count) or 25, #db.trace)
    ns:Print(("last %d trace entries:"):format(count))
    for i = #db.trace - count + 1, #db.trace do
        local e = db.trace[i]
        ns:Print(("  %s  %-10s state=%-5s %s")
            :format(date("%H:%M:%S", e.t), tostring(e.event),
                    tostring(e.state), tostring(e.detail or "")))
    end
end

local function Handler(input)
    local cmd, rest = strsplit(" ", strtrim(input or ""), 2)
    cmd = strlower(cmd or "")

    if cmd == "" or cmd == "status" then
        Status()

    elseif cmd == "inspect" then
        -- A file that fails to load is skipped silently by the client, which
        -- would otherwise make this command appear to do nothing at all.
        if ns.UI then
            ns.UI:Toggle()
        else
            ns:Print("|cffff5555Inspect.lua did not load|r - "
                  .. "run /console scriptErrors 1 and /reload to see why")
        end

    elseif cmd == "trace" then
        DumpTrace(rest)

    elseif cmd == "debug" then
        ns.db.settings.debug = not ns.db.settings.debug
        ns:Print("debug " .. (ns.db.settings.debug and "on" or "off"))

    elseif cmd == "autolog" then
        -- Routed through the setter so the slash command and the viewer menu
        -- do the same thing, including forcing advanced logging.
        local on = ns:SetAutoLog(strlower(rest or "") ~= "off")
        ns:Print("autoLog " .. (on and "on" or "off"))

    elseif cmd == "reset" then
        -- Recovery path for when chunks were generated by a defective build.
        -- An empty cache and no floor is the addon saying it holds nothing and
        -- wants everything, which is what makes the application re-read the
        -- logs in full rather than resuming from its stored offsets.
        -- Recorder match records are deliberately kept: they cannot be
        -- regenerated from anything.
        wipe(ns.db.cache)
        ns.db.oldestWanted = ""
        ns:Print("cache cleared and floor lowered; recorder records kept")
        ns:Print("now |cffffcc00/reload|r, run the application, then |cffffcc00/reload|r again")

    elseif cmd == "wipe" then
        -- Deleting the file on disk is not enough while the client is running:
        -- SavedVariables are written from memory at logout, so the old contents
        -- would simply reappear. This clears the in-memory table as well.
        if strlower(rest or "") ~= "confirm" then
            ns:Print("|cffff5555wipe erases recorded match data permanently|r - "
                  .. "rated status, results and rosters cannot be regenerated "
                  .. "from logs.")
            ns:Print(("currently holding %d match record(s). Type "
                  .. "|cffffcc00/combatsession wipe confirm|r to proceed.")
                  :format(#ns.db.matches))
        else
            wipe(ns.db.cache)
            wipe(ns.db.matches)
            wipe(ns.db.trace)
            ns.db.oldestWanted = ""
            ns:Print("all stored data cleared - |cffffcc00/reload|r to write it out")
        end

    elseif cmd == "sessions" then
        local ok, err = ns.API:SetMaxSessions(rest)
        if ok then
            ns:Print("session cap set to " .. ns.API:GetMaxSessions())
        else
            ns:Print(("session cap is %d (%s)"):format(ns.API:GetMaxSessions(), err))
        end

    else
        ns:Print("usage: /combatsession [status | inspect | trace [n] | "
              .. "sessions <n> | reset | wipe | debug | autolog on|off]")
    end
end

SLASH_COMBATSESSION1 = "/combatsession"
SLASH_COMBATSESSION2 = "/csession"
SlashCmdList["COMBATSESSION"] = Handler
